services:
    hook.twig.extension:
        class: HookBundle\Twig\HookExtension
        arguments: ["@doctrine.orm.entity_manager","@module.manager"]
        tags:
            - { name: twig.extension }
