<?php

namespace HookBundle\Repository;

/**
 * HookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HookRepository extends \Doctrine\ORM\EntityRepository
{
}
