<?php

namespace HookBundle\Repository;

/**
 * HookModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HookModuleRepository extends \Doctrine\ORM\EntityRepository
{
}
