content_article:
    resource: "@ContentBundle/Controller/ArticleController.php"
    type:     annotation

route:
    resource: "@RouteBundle/Controller/"
    type:     annotation
    prefix:   /

template:
    resource: "@TemplateBundle/Controller/"
    type:     annotation
    prefix:   /templates

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
